title: Parker Otto
description: GIS Fellow and Graduate Research Coordinator
site_title: 'Portfolio - Parker Otto'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: parkerotto
blog_url: 
email: parkerekotto@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 